name: Deploy sync api

on:
  push:
    branches:
      - sandbox
      - integration
      - staging
      - production

jobs:
  deploy_sync_api:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Set Environment Variables
        run: |
          stage=$(git rev-parse --abbrev-ref HEAD)
          echo "STAGE=${stage}" >> $GITHUB_ENV
          echo "WORKING_DIRECTORY=./" >> $GITHUB_ENV
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install NPM dependencies
        run: |
          cd $WORKING_DIRECTORY
          npm install
      - name: serverless deploy
        run: |
          cd $WORKING_DIRECTORY
          echo "The Stage is ${STAGE}"
          pip install pipenv
          serverless deploy --stage ${STAGE}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SLS_DEBUG: "*"
