app: learning
service: hello
org: sabiai

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  environment:
    DB_PASSWORD: ${ssm:/my_secrets/secret_phrase}

functions:
  hello:
    name: hello
    handler: hello.handler
